default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/trackday_v1_dev.sqlite3

  # adapter: postgresql
  # database: trackday_dev
  # host: localhost
  # port: 5433
  # username: apptest
  # password: password1

test:
  <<: *default
  adapter: sqlite3
  database: db/trackday_v1_test.sqlite3

  # adapter: postgresql
  # database: trackday_test

production:
  <<: *default
  adapter: postgresql
  database: trackday_v1_prod
  username: trackday
  password: <%= ENV['APP_POSTGRES_DATABASE_PASSWORD'] %>
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"